services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VIEW_DISTANCE: 10
      MEMORY: 2G
      PAPER_CONFIG_REPO: "RAW URL from your repo" # <--- Use this env var if you want to set the paper config for yourself (You only need just one, if you use both env vars PAPER_OPTIMIZE have more priority)
      PAPER_OPTIMIZE: "TRUE" # <--- you can use this env var set true if you want to use the Alpha018 Repo in https://github.com/Alpha018/paper-config-optimized

    ports:
      - "25565:25565"
    volumes:
      - mc-paper:/data
    restart: unless-stopped
volumes:
  mc-paper: {}
